unpackaged/main/default/objects/Crisis_Details__c/Crisis_Details__c.object-meta.xml
<CustomObject>
    <label>Crisis Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Crisis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crisis Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Crisis_Details__c/fields/Crisis_Number__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Crisis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Crisis_Details__c/fields/Crisis_Type__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Type__c</fullName>
    <label>Crisis Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drowning</fullName>
            </value>
            <value>
                <fullName>Construction Disaster</fullName>
            </value>
            <value>
                <fullName>Construction Accident</fullName>
            </value>
            <value>
                <fullName>Slip &amp; Fall</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Armed Robbery</fullName>
            </value>
            <value>
                <fullName>Shooting</fullName>
            </value>
            <value>
                <fullName>Fight</fullName>
            </value>
            <value>
                <fullName>Suspicious Package</fullName>
            </value>
            <value>
                <fullName>Bomb Threat</fullName>
            </value>
            <value>
                <fullName>Food Tampering</fullName>
            </value>
            <value>
                <fullName>Hostage situation</fullName>
            </value>
            <value>
                <fullName>Workplace Violence</fullName>
            </value>
            <value>
                <fullName>Discrimination</fullName>
            </value>
            <value>
                <fullName>Sexual Harassment</fullName>
            </value>
            <value>
                <fullName>Food Poisoning/Food Contamination</fullName>
            </value>
            <value>
                <fullName>Board of Health</fullName>
            </value>
            <value>
                <fullName>Health Related</fullName>
            </value>
            <value>
                <fullName>Health Department</fullName>
            </value>
            <value>
                <fullName>Suicide Call</fullName>
            </value>
            <value>
                <fullName>Death on Site</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Natural Disaster</fullName>
            </value>
            <value>
                <fullName>Explosion</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CrisisDetailTrgHandlerTest.cls
/*-------------------------------------------------------------------------------------------------
Author:             Danish QaimKhani
Date:               03-march-2021
Version:            1.0
Description:        Test Class for CrisisDetailTrgHandler 
----------------------------------------------------------------------------------------------------*/
/************************MODIFICATION HISTORY*************************************
Added on                Added By                Description
**********************************************************************************
03-march-2021            Danish QaimKhani                   Initial                     
**********************************************************************************/
@isTest
private class CrisisDetailTrgHandlerTest {
    
    @isTest static void test_method1() {
        
         Crisis_Details__c CDobj = new Crisis_Details__c();
		CDobj.Name='test'; 
        CDobj.Crisis_Number__c='123';
        CDobj.Crisis_Type__c='Drowning';
        
        insert CDobj;
        
        CDobj.Crisis_Number__c='456';
        
        update CDobj;

        
    }

}