unpackaged/main/default/objects/Account/fields/Location_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Franchise_Managed_Account.recordType-meta.xml
<RecordType>
    <fullName>Franchise_Managed_Account</fullName>
    <active>true</active>
    <description>Represents the franchises and managed locations</description>
    <label>Franchise &amp; Managed Location Account</label>
</RecordType>

unpackaged/main/default/objects/Administration_Data__c/Administration_Data__c.object-meta.xml
<CustomObject>
    <description>To control property wise time management to case create</description>
    <label>Admin Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Administration_Data__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Property Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Crisis_Details__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crisis Details</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Crisis_Details__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Crisis_Details__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Crisis_Number__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Crisis Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Crisis_Type__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Crisis Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Is_related_to_Crisis__c.field-meta.xml
<CustomField>
    <fullName>Is_related_to_Crisis__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is related to Crisis</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Franchise &amp; Managed Location Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Location_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Number__c</fullName>
    <formula>Location__r.Location_Number__c</formula>
    <label>Location Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Status_Updated_Time__c.field-meta.xml
<CustomField>
    <fullName>Status_Updated_Time__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Status Updated Time</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Loyalty.recordType-meta.xml
<RecordType>
    <fullName>Loyalty</fullName>
    <active>true</active>
    <businessProcess>Support Process Loyalty</businessProcess>
    <label>Loyalty</label>
</RecordType>

unpackaged/main/default/objects/Crisis_Details__c/Crisis_Details__c.object-meta.xml
<CustomObject>
    <label>Crisis Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Crisis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crisis Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Crisis_Details__c/fields/Crisis_Number__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Crisis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Crisis_Details__c/fields/Crisis_Type__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Type__c</fullName>
    <label>Crisis Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drowning</fullName>
            </value>
            <value>
                <fullName>Construction Disaster</fullName>
            </value>
            <value>
                <fullName>Construction Accident</fullName>
            </value>
            <value>
                <fullName>Slip &amp; Fall</fullName>
            </value>
            <value>
                <fullName>Terrorism</fullName>
            </value>
            <value>
                <fullName>Armed Robbery</fullName>
            </value>
            <value>
                <fullName>Shooting</fullName>
            </value>
            <value>
                <fullName>Fight</fullName>
            </value>
            <value>
                <fullName>Suspicious Package</fullName>
            </value>
            <value>
                <fullName>Bomb Threat</fullName>
            </value>
            <value>
                <fullName>Food Tampering</fullName>
            </value>
            <value>
                <fullName>Hostage situation</fullName>
            </value>
            <value>
                <fullName>Workplace Violence</fullName>
            </value>
            <value>
                <fullName>Discrimination</fullName>
            </value>
            <value>
                <fullName>Sexual Harassment</fullName>
            </value>
            <value>
                <fullName>Food Poisoning/Food Contamination</fullName>
            </value>
            <value>
                <fullName>Board of Health</fullName>
            </value>
            <value>
                <fullName>Health Related</fullName>
            </value>
            <value>
                <fullName>Health Department</fullName>
            </value>
            <value>
                <fullName>Suicide Call</fullName>
            </value>
            <value>
                <fullName>Death on Site</fullName>
            </value>
            <value>
                <fullName>Fire</fullName>
            </value>
            <value>
                <fullName>Natural Disaster</fullName>
            </value>
            <value>
                <fullName>Explosion</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Escalation_Admin_Table__c/Escalation_Admin_Table__c.object-meta.xml
<CustomObject>
    <label>Escalation Admin Table</label>
    <nameField>
        <displayFormat>ESC-{00000}</displayFormat>
        <label>Escalation Admin Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalation Admin Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/CaseEscalation_BatchTest.cls
/*-------------------------------------------------------------------------------------------------
Author:             Danish QaimKhani
Date:               03-march-2021
Version:            1.0
Description:        Test Class for CaseEscalation_Batch
----------------------------------------------------------------------------------------------------*/
/************************MODIFICATION HISTORY*************************************
Added on                Added By                Description
**********************************************************************************
03-march-2021            Danish QaimKhani                   Initial                     
**********************************************************************************/
@isTest (SeeAllData=false)
private class CaseEscalation_BatchTest {
    
    @isTest static void test_method1(){
         list<Escalation_Admin_Table__c> ListOfCaseTableData = DataFactoryTest.testgetEscalationAdminTableData(); 
        list<Administration_Data__c> ListOfAdminData = DataFactoryTest.testgetAdministrationData(); 
        
        List<Account> ListOfAccount = new List<Account>();
        
        ListOfAccount.add(new Account(Name= 'test Account 5',Location_Number__c='1237',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 6',Location_Number__c='1238',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 7',Location_Number__c='1239',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 8',Location_Number__c='1210',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
       
        insert ListOfAccount;
        
        Crisis_Details__c CDobj = new Crisis_Details__c();
		CDobj.Name='test'; 
        CDobj.Crisis_Number__c='123';
        CDobj.Crisis_Type__c='Drowning';
        
        insert CDobj;
        
        CDobj.Crisis_Number__c='1231234';
        update CDobj;
        if(ListOfAdminData[0].Property_Id__c != null)
        	DataFactoryTest.testgetContactWithAccountRelationShipList('Franchise_Managed_Property_Employee',ListOfAccount[0].Id,ListOfAdminData[0].Property_Id__c);
         
        list<Case> ListCase = DataFactoryTest.testgetCaseList('Loyalty');
        Integer i=0;
        for(Case row:ListCase){
            row.Status='In Progress';
            row.Status_Updated_Time__c=system.now().addMinutes(-120);
            if(i==0 || i==1)
            {
                row.Is_related_to_Crisis__c=true;
                row.Crisis_Details__c=CDobj.Id;
            }    
			i++;
        }
        	update ListCase;
        
        Test.startTest();
         Database.executeBatch(new CaseEscalation_Batch(), 200);

    }
    
    @isTest static void test_method2(){
         list<Escalation_Admin_Table__c> ListOfCaseTableData = DataFactoryTest.testgetEscalationAdminTableData(); 
        list<Administration_Data__c> ListOfAdminData = DataFactoryTest.testgetAdministrationData(); 
        
        List<Account> ListOfAccount = new List<Account>();
        
        ListOfAccount.add(new Account(Name= 'test Account 5',Location_Number__c='1211',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 6',Location_Number__c='1221',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 7',Location_Number__c='1231',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 8',Location_Number__c='1241',RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Franchise_Managed_Account').getRecordTypeId()));
       
        insert ListOfAccount;
        
        Crisis_Details__c CDobj = new Crisis_Details__c();
		CDobj.Name='test'; 
        CDobj.Crisis_Number__c='123';
        CDobj.Crisis_Type__c='Drowning';
        
        insert CDobj;
        
       
       DataFactoryTest.testgetContactWithAccountRelationShipList('Franchise_Managed_Property_Employee',ListOfAccount[0].Id,ListOfAccount[1].Id);
         
        list<Case> ListCase = DataFactoryTest.testgetCaseList('Loyalty');
        Integer i=0;
        for(Case row:ListCase){
            row.Status='In Progress';
            row.Status_Updated_Time__c=system.now().addMinutes(-120);
            row.Location__c=ListOfAccount[1].Id;
            if(i==0 || i==1)
            {
                row.Is_related_to_Crisis__c=true;
                row.Crisis_Details__c=CDobj.Id;
            }    
			i++;
        }
        	update ListCase;
        
        Test.startTest();
         Database.executeBatch(new CaseEscalation_Batch(), 200);

    }
    
    
    
}