unpackaged/main/default/objects/Account/fields/Location_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Location Number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Account/recordTypes/Franchise_Managed_Account.recordType-meta.xml
<RecordType>
    <fullName>Franchise_Managed_Account</fullName>
    <active>true</active>
    <description>Represents the franchises and managed locations</description>
    <label>Franchise &amp; Managed Location Account</label>
</RecordType>

unpackaged/main/default/objects/AccountContactRelation/fields/Email_Notifications__c.field-meta.xml
<CustomField>
    <fullName>Email_Notifications__c</fullName>
    <label>Email Notifications</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Cases (Crisis &amp; Non-Crisis)</fullName>
            </value>
            <value>
                <fullName>Only Crisis Cases</fullName>
            </value>
            <value>
                <fullName>Non-Crisis Cases</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/AccountContactRelation/fields/Escalation_Level__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Level__c</fullName>
    <label>Escalation Level</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Team Member</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>VP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/Administration_Data__c.object-meta.xml
<CustomObject>
    <description>To control property wise time management to case create</description>
    <label>Admin Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Administration_Data__c/fields/Case_Priority__c.field-meta.xml
<CustomField>
    <fullName>Case_Priority__c</fullName>
    <label>Case Priority</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Normal</fullName>
            </value>
            <value>
                <fullName>Low</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <label>Case Record Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E_Commerce</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>GX360_Survey</fullName>
                <label>GX360 Survey</label>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Medallia_Alert_Types__c.field-meta.xml
<CustomField>
    <fullName>Medallia_Alert_Types__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Medallia Alert Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Property_Id__c.field-meta.xml
<CustomField>
    <fullName>Property_Id__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Property Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Reason_for_Contacting__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Contacting__c</fullName>
    <label>Reason for Contacting</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer Service</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>Location Accessibility</fullName>
            </value>
            <value>
                <fullName>General Inquiry</fullName>
            </value>
            <value>
                <fullName>Question or Concern</fullName>
            </value>
            <value>
                <fullName>Website Issue or Feedback</fullName>
            </value>
            <value>
                <fullName>Human Resources</fullName>
            </value>
            <value>
                <fullName>Other/Miscellaneous</fullName>
            </value>
            <value>
                <fullName>Public Relations &amp; Advertising</fullName>
            </value>
            <value>
                <fullName>Rock Spa</fullName>
            </value>
            <value>
                <fullName>Sales/Catering/Meetings</fullName>
            </value>
            <value>
                <fullName>Security</fullName>
            </value>
            <value>
                <fullName>Seminole Wild Card Online</fullName>
            </value>
            <value>
                <fullName>Login Info &amp; Support</fullName>
            </value>
            <value>
                <fullName>Benefits</fullName>
            </value>
            <value>
                <fullName>Promotion Question</fullName>
            </value>
            <value>
                <fullName>Comp Dollars, Tier Points, or Free Play Questions</fullName>
            </value>
            <value>
                <fullName>Hotel Offers and Reservations</fullName>
            </value>
            <value>
                <fullName>Returns &amp; Refunds</fullName>
            </value>
            <value>
                <fullName>Product Info</fullName>
            </value>
            <value>
                <fullName>Shipping Questions</fullName>
            </value>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Online Support</fullName>
            </value>
            <value>
                <fullName>Dining</fullName>
            </value>
            <value>
                <fullName>Entertainment &amp; Hard Rock Live</fullName>
            </value>
            <value>
                <fullName>Gaming (Slots, Tables, Poker)</fullName>
            </value>
            <value>
                <fullName>Hotel</fullName>
            </value>
            <value>
                <fullName>Entertainment</fullName>
            </value>
            <value>
                <fullName>Gaming (Bingo, Slots, Tables, Poker)</fullName>
            </value>
            <value>
                <fullName>Win/Loss Statement Requests</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Receiver_Email__c.field-meta.xml
<CustomField>
    <fullName>Receiver_Email__c</fullName>
    <description>When the user sends an email for Email To Case and receives the email from the same email address it will help us to select email template to response</description>
    <encryptionScheme>None</encryptionScheme>
    <label>Receiver Email / Sender</label>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Trackable_Statuses__c.field-meta.xml
<CustomField>
    <fullName>Trackable_Statuses__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Trackable Statuses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Un_Trackable_Statuses__c.field-meta.xml
<CustomField>
    <fullName>Un_Trackable_Statuses__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Un-Trackable Statuses</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Use_For__c.field-meta.xml
<CustomField>
    <fullName>Use_For__c</fullName>
    <label>Use For</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medallia Property</fullName>
            </value>
            <value>
                <fullName>Case Escalation</fullName>
            </value>
            <value>
                <fullName>Medallia Alert Type</fullName>
            </value>
            <value>
                <fullName>Case Priority With Case Type</fullName>
            </value>
            <value>
                <fullName>Medallia Case Status</fullName>
            </value>
            <value>
                <fullName>WebForms Property</fullName>
            </value>
            <value>
                <fullName>Medallia Survey Progress</fullName>
            </value>
            <value>
                <fullName>Omni Channel</fullName>
            </value>
            <value>
                <fullName>Email To Case Template Selection</fullName>
            </value>
            <value>
                <fullName>Executive Escalation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Webform_Link__c.field-meta.xml
<CustomField>
    <fullName>Webform_Link__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Webform Link</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Case_Escalation.recordType-meta.xml
<RecordType>
    <fullName>Case_Escalation</fullName>
    <active>true</active>
    <label>Case Escalation</label>
</RecordType>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Case_Priority_With_Case_Type.recordType-meta.xml
<RecordType>
    <fullName>Case_Priority_With_Case_Type</fullName>
    <active>true</active>
    <label>Case Priority With Case Type</label>
</RecordType>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Email_To_Case_Template_Selection.recordType-meta.xml
<RecordType>
    <fullName>Email_To_Case_Template_Selection</fullName>
    <active>true</active>
    <description>Using to decide which Email Template should be sent</description>
    <label>Email To Case Template Selection</label>
</RecordType>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Executive_Escalation.recordType-meta.xml
<RecordType>
    <fullName>Executive_Escalation</fullName>
    <active>true</active>
    <description>To make a case using from and to addresses (Executive)</description>
    <label>Executive Escalation</label>
</RecordType>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Medallia_Case.recordType-meta.xml
<RecordType>
    <fullName>Medallia_Case</fullName>
    <active>true</active>
    <label>Medallia Case</label>
</RecordType>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Web_Forms_Property.recordType-meta.xml
<RecordType>
    <fullName>Web_Forms_Property</fullName>
    <active>true</active>
    <description>To decide  property data coming from web to forms.</description>
    <label>Web Forms Property</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Escalation_Level__c.field-meta.xml
<CustomField>
    <fullName>Escalation_Level__c</fullName>
    <label>Escalation Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Lead Team Member</fullName>
            </value>
            <value>
                <fullName>Supervisor</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>VP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Is_Junk_Case__c.field-meta.xml
<CustomField>
    <fullName>Is_Junk_Case__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Junk Case</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Location_Number__c.field-meta.xml
<CustomField>
    <fullName>Location_Number__c</fullName>
    <formula>Location__r.Location_Number__c</formula>
    <label>Location Number</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/System_Contact_First_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Contact_First_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Contact First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/System_Contact_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Contact_Last_Name__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System Contact Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/System_W2C_Website__c.field-meta.xml
<CustomField>
    <fullName>System_W2C_Website__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>System W2C Website</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Loyalty.recordType-meta.xml
<RecordType>
    <fullName>Loyalty</fullName>
    <active>true</active>
    <businessProcess>Support Process Loyalty</businessProcess>
    <label>Loyalty</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Other.recordType-meta.xml
<RecordType>
    <fullName>Other</fullName>
    <active>true</active>
    <businessProcess>Support Process Other</businessProcess>
    <label>Other</label>
</RecordType>

unpackaged/main/default/objects/Case/recordTypes/Service.recordType-meta.xml
<RecordType>
    <fullName>Service</fullName>
    <active>true</active>
    <businessProcess>Support Process Service</businessProcess>
    <label>Service</label>
</RecordType>

unpackaged/main/default/objects/Escalation_Admin_Table__c/Escalation_Admin_Table__c.object-meta.xml
<CustomObject>
    <label>Escalation Admin Table</label>
    <nameField>
        <displayFormat>ESC-{00000}</displayFormat>
        <label>Escalation Admin Table Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Escalation Admin Table</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Escalation_Admin_Table__c/fields/Case_Record_Type__c.field-meta.xml
<CustomField>
    <fullName>Case_Record_Type__c</fullName>
    <description>Please Use the Record type developer name here.</description>
    <label>Case Record Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>E_Commerce</fullName>
                <label>E-Commerce</label>
            </value>
            <value>
                <fullName>GX360_Survey</fullName>
                <label>GX360 Survey</label>
            </value>
            <value>
                <fullName>Loyalty</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Medallia_Staging__c/Medallia_Staging__c.object-meta.xml
<CustomObject>
    <description>Junction object for Medallia</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Medallia_Staging__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
</CustomField>

unpackaged/main/default/objects/Medallia_Staging__c/fields/First_name__c.field-meta.xml
<CustomField>
    <fullName>First_name__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>First name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Medallia_Staging__c/fields/Last_name__c.field-meta.xml
<CustomField>
    <fullName>Last_name__c</fullName>
    <encryptionScheme>CaseInsensitiveDeterministicEncryption</encryptionScheme>
    <label>Last name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/DataFactoryTest.cls
/*

Description : This class will help to create test data and return it to its calling class.

*/ 
@isTest
public class DataFactoryTest
{
     public static list<Account> testgetAccountList(String RecordtypeParam)
    {
        List<Account> ListOfAccount = new List<Account>();
        
        ListOfAccount.add(new Account(Name= 'test Account 1',Location_Number__c='1_'+ Math.round((Math.random() * (900000) + 100000)),RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 2',Location_Number__c='2_'+ Math.round((Math.random() * (900000) + 100000)),RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 3',Location_Number__c='3_'+ Math.round((Math.random() * (900000) + 100000)),RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
        ListOfAccount.add(new Account(Name= 'test Account 4',Location_Number__c='4_'+ Math.round((Math.random() * (900000) + 100000)),RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
       
        insert ListOfAccount;
        return ListOfAccount;
    }
    
    public static list<Contact> testgetContactList(String RecordtypeParam)
    {
        List<Contact> ListOfContact = new List<Contact>();
        
        ListOfContact.add(new Contact(LastName= 'test Account 1',FirstName='test',Email = 'test1@gmail.com', MailingPostalCode = '10001',RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
        ListOfContact.add(new Contact(LastName= 'test Account 2',FirstName='test',Email = 'test2@gmail.com',RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
        
        
        insert ListOfContact;
        return ListOfContact;
    }
    
     public static list<Case> testgetCaseList(String RecordtypeParam)
    {
        List<Case> ListOfCases = new List<Case>();
        
        ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='new'));
        ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='new'));
        ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='new'));
        ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='Pending',Origin='Email',SuppliedEmail='danish.qaimkhani@getteconic.com',ContactId=null));
        ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='Pending',Origin='Email',SuppliedEmail='danish.qaimkhani@getteconic.com',ContactId=null));
		ListOfCases.add(new Case(Subject='Test Controller Acct Case urgent',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='Pending',Origin='Email',SuppliedEmail='danish.qaimkhani@getteconic.com',ContactId=null));
        ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='Pending',Origin='Email',SuppliedEmail='danish.qaimkhani@getteconic.com',ContactId=null,Is_Junk_Case__c=true));
        ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='Pending',Origin='Web',SuppliedEmail='danish.qaimkhani@getteconic.com',ContactId=null,System_W2C_Website__c='abc',Reason='Customer Service',SuppliedPhone='123'));
		ListOfCases.add(new Case(Subject='Test Controller Acct Case',RecordTypeId = Schema.SObjectType.Case.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId(),Status='Pending',Origin='Web',SuppliedEmail='test3@gmail.com',ContactId=null,System_W2C_Website__c='InternalWebForm',Reason='Loyalty',SuppliedPhone='123',System_Contact_Last_Name__c='test Account 2',System_Contact_First_Name__c='test'));
        insert ListOfCases;
        return ListOfCases;
    }
    public static list<Administration_Data__c> testgetAdministrationData(){
        List<Account> ListOfAccount = testgetAccountList('Franchise_Managed_Account');
        List<Administration_Data__c> ListOfAdminData = new List<Administration_Data__c>();
        EmailTemplate templateId = [Select id,DeveloperName from EmailTemplate limit 1];
        
        // do not change 0 index using it batch escalation test class
        ListOfAdminData.add(new Administration_Data__c(Name='CaseEscalationSetup',use_for__c='Case Escalation',Property_Id__c=ListOfAccount[0].Id,Trackable_Statuses__c='In Progress,Pending,Pending Guest,Pending Internal,Pending Warehouse,Pending Shipper,Pending Shipper Secondary,Pending Warehouse Secondary,Pending Internal Secondary,Pending,Guest Secondary,Pending Onsite Property Team Member,Paused Crisis,Paused Other,Responded,Reopened',Un_Trackable_Statuses__c='Resolved,New,Closed',RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Case_Escalation').getRecordTypeId()) );
        ListOfAdminData.add(new Administration_Data__c(Name='Medallia alert type transform to case High',use_for__c='Medallia Alert Type',Medallia_Alert_Types__c='Detractor | Elite or R2,Passive | Elite or R2,Promoter | Elite or R2,Detractor | X or Rank 1,Passive | X or Rank 1,Promoter | X or Rank 1',Case_Priority__c ='High',RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Medallia_Case').getRecordTypeId() ) );
		ListOfAdminData.add(new Administration_Data__c(Name='Medallia alert type transform to case High',use_for__c='Medallia Alert Type',Medallia_Alert_Types__c='Detractor | Elite or R2,Passive | Elite or R2,Promoter | Elite or R2,Detractor | X or Rank 1,Passive | X or Rank 1,Promoter | X or Rank 1',Case_Priority__c ='High',RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Medallia_Case').getRecordTypeId() ) );
        ListOfAdminData.add(new Administration_Data__c(Name='test',use_for__c='Case Priority With Case Type',Webform_Link__c='abc',Case_Priority__c ='High', Reason_for_Contacting__c='Customer Service', Case_Record_Type__c='Loyalty',RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Case_Priority_With_Case_Type').getRecordTypeId() ) );
		ListOfAdminData.add(new Administration_Data__c(Name='test2',use_for__c='WebForms Property',Webform_Link__c='abc',Property_Id__c=ListOfAccount[0].Id,RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Web_Forms_Property').getRecordTypeId() ) );
		ListOfAdminData.add(new Administration_Data__c(Name='test4',use_for__c='WebForms Property',Webform_Link__c='abc',Property_Id__c=ListOfAccount[0].Id,RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Web_Forms_Property').getRecordTypeId() ) );
		ListOfAdminData.add(new Administration_Data__c(Name='test3',use_for__c='WebForms Property',Webform_Link__c='abc',Receiver_Email__c=Label.System_Org_Wide_Email_Address,Email_Template_Name__c=templateId.DeveloperName,Property_Id__c=ListOfAccount[0].Id,RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Web_Forms_Property').getRecordTypeId() ) );
	    ListOfAdminData.add(new Administration_Data__c(Name='test5',use_for__c='Email To Case Template Selection',Receiver_Email__c=Label.System_Org_Wide_Email_Address,Email_Template_Name__c=templateId.DeveloperName,Property_Id__c=ListOfAccount[0].Id,RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Email_To_Case_Template_Selection').getRecordTypeId() ) );
        insert ListOfAdminData;
        return ListOfAdminData;
    }
    
    public static list<Contact> testgetContactWithAccountRelationShipList(String RecordtypeParam,String Accid ,String AccountIdparam)
    {
        List<Contact> ListOfContact = new List<Contact>();
        AccountContactRelation acr =new AccountContactRelation();
        // AccountId=AccountIdparam ,
        ListOfContact.add(new Contact(LastName= 'test  1', AccountId=Accid , FirstName='test1',Email = 'test1@gmail.com', MailingPostalCode = '10001',RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
        ListOfContact.add(new Contact(LastName= 'test  2', AccountId=Accid ,  FirstName='test2',Email = 'test2@gmail.com',RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
		ListOfContact.add(new Contact(LastName= 'test  3', AccountId=Accid ,  FirstName='test3',Email = 'test3@gmail.com',RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get(RecordtypeParam).getRecordTypeId()));
        
        
        insert ListOfContact;
        
        List<AccountContactRelation> ListOfContactRelationShip = new List<AccountContactRelation>();
       integer i=0;
       /* for(Contact row:ListOfContact){
             acr =  new AccountContactRelation();
            
            acr.Contactid=row.Id;
            acr.Accountid=row.AccountId;
            if(i==0)
            	acr.Email_Notifications__c='All Cases (Crisis & Non-Crisis)';
            if(i==1)
            	acr.Email_Notifications__c='Non-Crisis Cases';
            if(i>1)
            	acr.Email_Notifications__c='Only Crisis Cases';
            acr.Escalation_Level__c='Lead Team Member; Supervisor; Manager; Director; VP';
            
            ListOfContactRelationShip.add(acr);
            
            i++;
        }*/
        
        acr =  new AccountContactRelation();
            
            acr.Contactid=ListOfContact[0].Id;
            acr.Accountid=AccountIdparam;
			acr.Email_Notifications__c='All Cases (Crisis & Non-Crisis)';
			acr.Escalation_Level__c='Lead Team Member; Supervisor; Manager; Director; VP';
        
         ListOfContactRelationShip.add(acr);
        
            acr =  new AccountContactRelation();
            
            acr.Contactid=ListOfContact[1].Id;
            acr.Accountid=AccountIdparam;
			acr.Email_Notifications__c='Non-Crisis Cases';
            acr.Escalation_Level__c='Lead Team Member; Supervisor; Manager; Director; VP';
         ListOfContactRelationShip.add(acr);
        
        	acr =  new AccountContactRelation();
            
            acr.Contactid=ListOfContact[2].Id;
            acr.Accountid=AccountIdparam;
			acr.Email_Notifications__c='Only Crisis Cases';
            acr.Escalation_Level__c='Lead Team Member; Supervisor; Manager; Director; VP';
        
        
         ListOfContactRelationShip.add(acr);
        
        
        insert ListOfContactRelationShip;
        return ListOfContact;
    }
    
    
    
    public static list<Escalation_Admin_Table__c> testgetEscalationAdminTableData(){
       
        List<Escalation_Admin_Table__c> ListOfAdminData = new List<Escalation_Admin_Table__c>();
        ListOfAdminData.add(new Escalation_Admin_Table__c(Case_Record_Type__c='Loyalty',Case_Status__c='In Progress',Escalation_Level__c='Lead Team Member',Tier__c='Premier',Time_Minutes__c=2) );
        ListOfAdminData.add(new Escalation_Admin_Table__c(Case_Record_Type__c='Loyalty',Case_Status__c='In Progress',Escalation_Level__c='Supervisor',Tier__c='Premier',Time_Minutes__c=2) );
        ListOfAdminData.add(new Escalation_Admin_Table__c(Case_Record_Type__c='Loyalty',Case_Status__c='In Progress',Escalation_Level__c='Manager',Tier__c='Premier',Time_Minutes__c=2) );
        ListOfAdminData.add(new Escalation_Admin_Table__c(Case_Record_Type__c='Loyalty',Case_Status__c='In Progress',Escalation_Level__c='Director',Tier__c='Premier',Time_Minutes__c=2) );
        ListOfAdminData.add(new Escalation_Admin_Table__c(Case_Record_Type__c='Loyalty',Case_Status__c='In Progress',Escalation_Level__c='VP',Tier__c='Premier',Time_Minutes__c=2) );
        insert ListOfAdminData;
        return ListOfAdminData;
    }
    
    public static Medallia_Staging__C SurveyResponseIns(Medallia_Staging__C ms,string SurveyId,string SRstatus){       
        //Medallia_Staging__C ms = new Medallia_Staging__C();
        ms.CASINO_ACCOUNT_NUMBER__C = '03082021-1307-10';
        ms.EMAIL__C = 'e.gomez10@testing.gmail.com';
        ms.FIRST_NAME__C = 'Easton';
        ms.LAST_NAME__C = 'Gomez';
        ms.Rank_Value__c = 20;
        ms.Survey_ID__c = SurveyId;
        ms.Responsedate__c = system.Date.today();
        ms.Record_Type_Seminole__c = 'RT Seminole';
        ms.Overall_Satisfaction_with_Property__c = 'Somewhat satisfied2';
        ms.Alert_type__c = 'Detractor | Elite or R2';
        ms.Current_status_of_alert__c = SRstatus;
        ms.Property__c = 'Hard Rock Hotel & Casino Atlantic City';
        ms.Rank__c = '09';
        ms.Tier__c='XCARD';
        return ms;
    }
    
    public static list<Administration_Data__c> testGetAdminDataForExecutiveEscalation(){
    
        List<Administration_Data__c> adminDataEEList = new List<Administration_Data__c>();
        
     	Administration_Data__c adminItem = new Administration_Data__c();
        adminItem.Name = 'Case Escalation For Test';
        adminItem.Use_For__c = 'Executive Escalation';
        adminItem.RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Executive_Escalation').getRecordTypeId();
        adminItem.From_Address__c = 'mok309@outlook.com';
        adminItem.To_Address__c = Label.System_Org_Wide_Email_Address;
        adminItem.Case_Record_Type__c = 'Other';
        adminItem.SF_Case_Status__c = 'General Hold';
        adminItem.Case_Priority__c = 'High';
        
        adminDataEEList.add(adminItem);
        
        return adminDataEEList;
        
    }    
    
    
}