unpackaged/main/default/objects/Account/recordTypes/Franchise_Managed_Account.recordType-meta.xml
<RecordType>
    <fullName>Franchise_Managed_Account</fullName>
    <active>true</active>
    <description>Represents the franchises and managed locations</description>
    <label>Franchise &amp; Managed Location Account</label>
</RecordType>

unpackaged/main/default/objects/Administration_Data__c/Administration_Data__c.object-meta.xml
<CustomObject>
    <description>To control property wise time management to case create</description>
    <label>Admin Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Case/fields/Action_Taken__c.field-meta.xml
<CustomField>
    <fullName>Action_Taken__c</fullName>
    <label>Action Taken</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Question Answered</fullName>
            </value>
            <value>
                <fullName>Seek Clarification</fullName>
            </value>
            <value>
                <fullName>Appeasement: Comp Dollars</fullName>
            </value>
            <value>
                <fullName>Appeasement: Room+</fullName>
            </value>
            <value>
                <fullName>Escalate</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Compassionate Response</fullName>
            </value>
            <value>
                <fullName>Appeasement: Room</fullName>
            </value>
            <value>
                <fullName>NCN—No Contact Necessary</fullName>
            </value>
            <value>
                <fullName>Folio Sent</fullName>
            </value>
            <value>
                <fullName>Appeasement Offered</fullName>
            </value>
            <value>
                <fullName>Points/Visit Added</fullName>
            </value>
            <value>
                <fullName>Refunded Item/Order</fullName>
            </value>
            <value>
                <fullName>Appeasement Credit</fullName>
            </value>
            <value>
                <fullName>Re-Ordered</fullName>
            </value>
            <value>
                <fullName>Sent Tracking</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Franchise &amp; Managed Location Account</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Problem_Area__c.field-meta.xml
<CustomField>
    <fullName>Problem_Area__c</fullName>
    <label>Problem Area</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FH: Attitude</fullName>
            </value>
            <value>
                <fullName>FH: Appearance</fullName>
            </value>
            <value>
                <fullName>FH: Accuracy</fullName>
            </value>
            <value>
                <fullName>FH: Attentiveness</fullName>
            </value>
            <value>
                <fullName>WT: Longer than expected (speed of service)</fullName>
            </value>
            <value>
                <fullName>WT: Longer than expected (line)</fullName>
            </value>
            <value>
                <fullName>QT: Value</fullName>
            </value>
            <value>
                <fullName>QT: Value (Marketing, SWC, Offer/Promo)</fullName>
            </value>
            <value>
                <fullName>QT: Variety</fullName>
            </value>
            <value>
                <fullName>QT: Cleanliness</fullName>
            </value>
            <value>
                <fullName>QT: Smell/Smoke/Air Quality/Temp/Volume</fullName>
            </value>
            <value>
                <fullName>QT: Malfunctioning or Broken or Missing</fullName>
            </value>
            <value>
                <fullName>QT: Security</fullName>
            </value>
            <value>
                <fullName>No Text</fullName>
            </value>
            <value>
                <fullName>QT: Taste/Temperature</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Reservations/Cancellations/Rates</fullName>
            </value>
            <value>
                <fullName>Billing Disputes</fullName>
            </value>
            <value>
                <fullName>Folio Requests</fullName>
            </value>
            <value>
                <fullName>Sales Inquiries—Groups</fullName>
            </value>
            <value>
                <fullName>General Information</fullName>
            </value>
            <value>
                <fullName>TA Commission</fullName>
            </value>
            <value>
                <fullName>Lost &amp; Found</fullName>
            </value>
            <value>
                <fullName>Guest Complaint</fullName>
            </value>
            <value>
                <fullName>Donation Requests</fullName>
            </value>
            <value>
                <fullName>Collaboration/Advertising Requests</fullName>
            </value>
            <value>
                <fullName>Vendor Requests</fullName>
            </value>
            <value>
                <fullName>Team Member Inquiries</fullName>
            </value>
            <value>
                <fullName>Employment Inquiries</fullName>
            </value>
            <value>
                <fullName>General Inquiries</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Reason_Text__c.field-meta.xml
<CustomField>
    <fullName>Reason_Text__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Reason</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Resolution__c.field-meta.xml
<CustomField>
    <fullName>Resolution__c</fullName>
    <label>Resolution</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added Credits</fullName>
            </value>
            <value>
                <fullName>Assigned Badge</fullName>
            </value>
            <value>
                <fullName>Appeasement Credit</fullName>
            </value>
            <value>
                <fullName>Denied  Lack of Evidence</fullName>
            </value>
            <value>
                <fullName>Denied  Other</fullName>
            </value>
            <value>
                <fullName>Pins</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Sent Tracking</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Cancelled Order</fullName>
            </value>
            <value>
                <fullName>Re Shipped Package</fullName>
            </value>
            <value>
                <fullName>No Response from Guest</fullName>
            </value>
            <value>
                <fullName>Compasionate Response</fullName>
            </value>
            <value>
                <fullName>Questions Answered</fullName>
            </value>
            <value>
                <fullName>Seek Clarification</fullName>
            </value>
            <value>
                <fullName>Appeasement Comp Dollars</fullName>
            </value>
            <value>
                <fullName>Appeasement Room</fullName>
            </value>
            <value>
                <fullName>Appeasement Room +</fullName>
            </value>
            <value>
                <fullName>Escalate</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
            <value>
                <fullName>Appeasement Credit (Value field to populate and required)</fullName>
                <isActive>false</isActive>
                <label>Appeasement Credit (Value field to populate and required)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Case/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Case/recordTypes/Loyalty.recordType-meta.xml
<RecordType>
    <fullName>Loyalty</fullName>
    <active>true</active>
    <businessProcess>Support Process Loyalty</businessProcess>
    <label>Loyalty</label>
</RecordType>

unpackaged/main/default/objects/Contact/recordTypes/Customer_Guest.recordType-meta.xml
<RecordType>
    <fullName>Customer_Guest</fullName>
    <active>true</active>
    <description>Represents customer and guest contacts</description>
    <label>Customer &amp; Guest</label>
</RecordType>

unpackaged/main/default/classes/EmailMessageTrgHandlerTest.cls
/*-------------------------------------------------------------------------------------------------
Author:             Danish QaimKhani
Date:               03-march-2021
Version:            1.0
Description:        Test Class for EmailMessageTrgHandler 
----------------------------------------------------------------------------------------------------*/
/************************MODIFICATION HISTORY*************************************
Added on                Added By                Description
**********************************************************************************
03-march-2021            Danish QaimKhani                   Initial                     
**********************************************************************************/
@isTest
public class EmailMessageTrgHandlerTest {
    
     @isTest static void test_insert() {
        list<Administration_Data__c> ListOfAdminData = DataFactoryTest.testgetAdministrationData();
         
        list<Contact> ListOfContact = DataFactoryTest.testgetContactList('Customer_Guest'); 
        list<Account> ListAccount = DataFactoryTest.testgetAccountList('Franchise_Managed_Account');
        
        list<Case> ListCase = DataFactoryTest.testgetCaseList('Loyalty');
        ListCase[0].Origin='Email'; 
        ListCase[0].SuppliedEmail='test@test.com';
        ListCase[0].Status='Closed';
        ListCase[0].Resolution__c='Added Credits'; 
        ListCase[0].Reason_Text__c ='test';  
		ListCase[0].Value__c ='test';
        ListCase[0].Location__c =ListAccount[0].Id;
        ListCase[0].Action_Taken__c ='Question Answered';
        ListCase[0].Problem_Area__c='FH: Attitude';
        ListCase[1].Status='Pending'; 
        ListCase[1].Origin='Email'; 
        ListCase[1].SuppliedEmail='test2@test.com';
        Update  ListCase;
         
         
         //Insert test case record
        Case c = new Case();
        c.Subject = 'Ok Test';
        c.Status ='New';
        c.Priority = 'Medium';
        c.Origin = 'Email';
        insert c;

        //Insert emailmessage for case
        EmailMessage email = new EmailMessage();
        email.FromAddress = 'test@abc.org';
        email.Incoming = True;
        email.ToAddress= Label.System_Org_Wide_Email_Address;
        email.Subject = 'Test email';
        email.HtmlBody = 'Test email body';
        email.ParentId = c.Id; 
        insert email;       
         
     	List<EmailMessage > listofEmailMessage = new List<EmailMessage >();
        
        listofEmailMessage.add(new EmailMessage(fromaddress='test12ss12@gmail.com', toAddress = ListOfContact[0].Email, subject = 'Opt Out Test Message', TextBody= 'This is the message body BR-Interno.', RelatedToId = ListCase[0].Id,Incoming=true));
        listofEmailMessage.add(new EmailMessage(fromaddress='test@test.com', toAddress = ListOfContact[0].Email, subject = 'Opt Out Test Message', TextBody= 'This is the message body BR-Interno.',Incoming=true));
        listofEmailMessage.add(new EmailMessage(fromaddress='test@test.com', toAddress = ListOfContact[0].Email, subject = 'Opt Out Test Message', TextBody= 'This is the message body BR-Interno.', RelatedToId = ListCase[1].Id,Incoming=true));
        listofEmailMessage.add(new EmailMessage(fromaddress='test@test.com', toAddress = 'test12ssam@gmail.com', subject = 'Opt Out Test Message', TextBody= 'This is the message body BR-Interno.'));
        listofEmailMessage.add(new EmailMessage(fromaddress='test@test.com', toAddress = Label.System_Org_Wide_Email_Address, RelatedToId = ListCase[1].Id, subject = 'Opt Out Test Message', TextBody= 'This is the message body BR-Interno.',Incoming=true));    
		
         insert listofEmailMessage;
         
        
		
	}
    
    //Code done for escalation cases - HRSC3AP-520 by Mustafa Quresh dated: 15/11/2021
     @isTest static void test_insert_executive_escalation() {  
       
        Test.StartTest(); 
         List<Administration_Data__c> adminDataEEList = DataFactoryTest.testGetAdminDataForExecutiveEscalation(); 
         Insert adminDataEEList;
         system.debug('admin data list: ' + adminDataEEList); 
         
         //Insert test case record
        Case c = new Case();
        c.Subject = 'Ok Test';
        c.Status ='New';
        c.Priority = 'Medium';
        c.Origin = 'Email';
        insert c;
         
         //Insert emailmessage for executive escalation case
        EmailMessage emailItem = new EmailMessage();
        emailItem.FromAddress = 'mok309@outlook.com';
        emailItem.Incoming = True;
        emailItem.ToAddress= Label.System_Org_Wide_Email_Address;
        emailItem.Subject = 'Test email';
        emailItem.HtmlBody = 'Test email body';
        emailItem.RelatedToId = c.Id; 
      
        insert emailItem;   
        
        
         
		Test.stopTest();         
     }
    
}