unpackaged/main/default/objects/Case/fields/Crisis_Details__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Crisis Details</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Crisis_Details__c.Is_Active__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Crisis_Details__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Case/fields/Crisis_Number__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Crisis Number</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Crisis_Details__c/Crisis_Details__c.object-meta.xml
<CustomObject>
    <label>Crisis Details</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Crisis Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crisis Details</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Crisis_Details__c/fields/Crisis_Number__c.field-meta.xml
<CustomField>
    <fullName>Crisis_Number__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Crisis Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CrisisDetailTrgHandler.cls
/*-------------------------------------------------------------------------------------------------
Author:             Danish QaimKhani
Date:               02-March-2021
Version:            1.0
Description:        Case Trigger Handler
----------------------------------------------------------------------------------------------------*/
/************************MODIFICATION HISTORY*************************************
Added on             Added By               Description
**********************************************************************************
02-March-2021         Danish QaimKhani          Added method that
adding crisis number with name
**********************************************************************************/

public class CrisisDetailTrgHandler {

    public void onBeforeInsert(List<Crisis_Details__c> newObjects, Map<Id, Crisis_Details__c> newMap){
      
        for(Crisis_Details__c row:newObjects){
            if(row.Crisis_Number__c !=null)
                row.Name=row.Crisis_Number__c +' ' +row.Name;
            
             row.Name=row.Name.left(80);
        }

    }
    
     public void onBeforeUpdate(List<Crisis_Details__c> oldObjects, List<Crisis_Details__c> newObjects, Map<Id, Crisis_Details__c> oldMap, Map<Id, Crisis_Details__c> newMap){
      	Crisis_Details__c OldRow;
        String tempCrisisNumber='';
		for(Crisis_Details__c row:newObjects){
            OldRow = oldMap.get( row.Id );
            tempCrisisNumber='';
            
            if(row.Crisis_Number__c != null)
            	tempCrisisNumber = String.valueOf(row.Crisis_Number__c)+' ';
          
            
            
            if( OldRow.Name !=row.Name ||  OldRow.Crisis_Number__c !=row.Crisis_Number__c)
            {     // checking if old data is not null so remove characters from name and add again
                if(OldRow.Crisis_Number__c !=null)
            		row.Name=row.Name.replace(String.valueOf(OldRow.Crisis_Number__c), '' );
                
                row.Name=tempCrisisNumber+row.Name;
                row.Name=row.Name.left(80);
            }
            
        }
         
     }
    
    
}