unpackaged/main/default/objects/Administration_Data__c/Administration_Data__c.object-meta.xml
<CustomObject>
    <description>To control property wise time management to case create</description>
    <label>Admin Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Administration_Data__c/fields/Progress_Bar_Color__c.field-meta.xml
<CustomField>
    <fullName>Progress_Bar_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Progress Bar Color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Rating_Score__c.field-meta.xml
<CustomField>
    <fullName>Rating_Score__c</fullName>
    <label>Rating Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Use_For__c.field-meta.xml
<CustomField>
    <fullName>Use_For__c</fullName>
    <label>Use For</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medallia Property</fullName>
            </value>
            <value>
                <fullName>Case Escalation</fullName>
            </value>
            <value>
                <fullName>Medallia Alert Type</fullName>
            </value>
            <value>
                <fullName>Case Priority With Case Type</fullName>
            </value>
            <value>
                <fullName>Medallia Case Status</fullName>
            </value>
            <value>
                <fullName>WebForms Property</fullName>
            </value>
            <value>
                <fullName>Medallia Survey Progress</fullName>
            </value>
            <value>
                <fullName>Omni Channel</fullName>
            </value>
            <value>
                <fullName>Email To Case Template Selection</fullName>
            </value>
            <value>
                <fullName>Executive Escalation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SurveyResponseProgressIndicator.cls
public class SurveyResponseProgressIndicator {
   @AuraEnabled
    public static list<String> getRatingScoreColor(){
        list<String> lstColor = new list<String>(); 
        For(Administration_Data__c row : [select Progress_Bar_Color__c from Administration_Data__c 
                                          where Use_For__c ='Medallia Survey Progress' order by Rating_Score__c]){           
			lstColor.add(row.Progress_Bar_Color__c);                                              
        }
        
          return lstColor;
      }
}