unpackaged/main/default/objects/Administration_Data__c/Administration_Data__c.object-meta.xml
<CustomObject>
    <description>To control property wise time management to case create</description>
    <label>Admin Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Administration_Data__c/fields/Progress_Bar_Color__c.field-meta.xml
<CustomField>
    <fullName>Progress_Bar_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Progress Bar Color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Rating_Score__c.field-meta.xml
<CustomField>
    <fullName>Rating_Score__c</fullName>
    <label>Rating Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Use_For__c.field-meta.xml
<CustomField>
    <fullName>Use_For__c</fullName>
    <label>Use For</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medallia Property</fullName>
            </value>
            <value>
                <fullName>Case Escalation</fullName>
            </value>
            <value>
                <fullName>Medallia Alert Type</fullName>
            </value>
            <value>
                <fullName>Case Priority With Case Type</fullName>
            </value>
            <value>
                <fullName>Medallia Case Status</fullName>
            </value>
            <value>
                <fullName>WebForms Property</fullName>
            </value>
            <value>
                <fullName>Medallia Survey Progress</fullName>
            </value>
            <value>
                <fullName>Omni Channel</fullName>
            </value>
            <value>
                <fullName>Email To Case Template Selection</fullName>
            </value>
            <value>
                <fullName>Executive Escalation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Medallia_Case.recordType-meta.xml
<RecordType>
    <fullName>Medallia_Case</fullName>
    <active>true</active>
    <label>Medallia Case</label>
</RecordType>

unpackaged/main/default/classes/SurveyResponseProgressIndicatorTest.cls
/*-------------------------------------------------------------------------------------------------
Author:             Shoukat Hussain
Date:               10-Mar-2021
Version:            1.0
Description:        Test Class for SurveyResponseProgressIndicator 
----------------------------------------------------------------------------------------------------*/
@isTest
public class SurveyResponseProgressIndicatorTest {
    @isTest 
    static void SR_Insert() {   
       list<Administration_Data__c> lstadmin = new list<Administration_Data__c>();
       integer myratingscore = 0;
         Id AdmindataRTid =  Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Medallia_Case').getRecordTypeId();                
       for (Integer i = 0, j = 0; i < 10; i++) {
    		lstadmin.add(new Administration_Data__c(name='Progress',rating_score__C=myratingscore,
                                                 progress_bar_color__C='red',Use_For__c='Medallia Survey Progress',
                                                RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Medallia_Case').getRecordTypeId() ));            
			myratingscore = myratingscore+1;
       }
        insert lstadmin;
        list<String> lstColor = new list<String>(); 
        lstColor =SurveyResponseProgressIndicator.getRatingScoreColor(); 
    }
    
}