unpackaged/main/default/objects/Administration_Data__c/Administration_Data__c.object-meta.xml
<CustomObject>
    <description>To control property wise time management to case create</description>
    <label>Admin Data</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Administration_Data__c/fields/Progress_Bar_Color__c.field-meta.xml
<CustomField>
    <fullName>Progress_Bar_Color__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Progress Bar Color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Rating_Score__c.field-meta.xml
<CustomField>
    <fullName>Rating_Score__c</fullName>
    <label>Rating Score</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/fields/Use_For__c.field-meta.xml
<CustomField>
    <fullName>Use_For__c</fullName>
    <label>Use For</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Medallia Property</fullName>
            </value>
            <value>
                <fullName>Case Escalation</fullName>
            </value>
            <value>
                <fullName>Medallia Alert Type</fullName>
            </value>
            <value>
                <fullName>Case Priority With Case Type</fullName>
            </value>
            <value>
                <fullName>Medallia Case Status</fullName>
            </value>
            <value>
                <fullName>WebForms Property</fullName>
            </value>
            <value>
                <fullName>Medallia Survey Progress</fullName>
            </value>
            <value>
                <fullName>Omni Channel</fullName>
            </value>
            <value>
                <fullName>Email To Case Template Selection</fullName>
            </value>
            <value>
                <fullName>Executive Escalation</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Administration_Data__c/recordTypes/Medallia_Case.recordType-meta.xml
<RecordType>
    <fullName>Medallia_Case</fullName>
    <active>true</active>
    <label>Medallia Case</label>
</RecordType>

unpackaged/main/default/objects/Case/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Medallia_Staging__c/Medallia_Staging__c.object-meta.xml
<CustomObject>
    <description>Junction object for Medallia</description>
    <label>Survey Response</label>
    <nameField>
        <displayFormat>SR-{00000000}</displayFormat>
        <label>Survey Response</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Survey Responses</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Medallia_Staging__c/fields/Current_status_of_alert__c.field-meta.xml
<CustomField>
    <fullName>Current_status_of_alert__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current status of alert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Medallia_Staging__c/fields/Rank__c.field-meta.xml
<CustomField>
    <fullName>Rank__c</fullName>
    <label>Rank</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
            </value>
            <value>
                <fullName>02</fullName>
            </value>
            <value>
                <fullName>03</fullName>
            </value>
            <value>
                <fullName>04</fullName>
            </value>
            <value>
                <fullName>05</fullName>
            </value>
            <value>
                <fullName>06</fullName>
            </value>
            <value>
                <fullName>07</fullName>
            </value>
            <value>
                <fullName>08</fullName>
            </value>
            <value>
                <fullName>09</fullName>
            </value>
            <value>
                <fullName>10</fullName>
            </value>
            <value>
                <fullName>11</fullName>
            </value>
            <value>
                <fullName>13</fullName>
            </value>
            <value>
                <fullName>12</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Medallia_Staging__c/fields/Tier__c.field-meta.xml
<CustomField>
    <fullName>Tier__c</fullName>
    <label>Tier</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Premier</fullName>
            </value>
            <value>
                <fullName>Platinum</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>XCARD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MedalliaStagingTrgHandlerTest.cls
/*-------------------------------------------------------------------------------------------------
Author:             Shoukat Hussain
Date:               10-Mar-2021
Version:            1.0
Description:        Test Class for MedalliaStagingTrgHandler and MedalliaStagingTrg
----------------------------------------------------------------------------------------------------*/
@isTest
public class MedalliaStagingTrgHandlerTest {
    @isTest static void SR_Insert() {  
        list<Administration_Data__c> lstadmin = new list<Administration_Data__c>();
        integer myratingscore = 0;
        Id AdmindataRTid =  Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Medallia_Case').getRecordTypeId();        
        for (Integer i = 0, j = 0; i < 10; i++) {
    		lstadmin.add(new Administration_Data__c(name='Progress',rating_score__C=myratingscore,
                                                 progress_bar_color__C='red',Use_For__c='Medallia Survey Progress',
                                                RecordTypeId = Schema.SObjectType.Administration_Data__c.getRecordTypeInfosByDeveloperName().get('Medallia_Case').getRecordTypeId() ));            
			myratingscore = myratingscore+1;
       }
        system.debug('check '+lstadmin);
        If(lstadmin.size()>0) insert lstadmin;
        
        
        Medallia_Staging__C ms = new Medallia_Staging__C();
        ms =  DataFactoryTest.SurveyResponseIns(ms,'001','New');
		insert ms;
		ms.Rank__c = '13';
        ms.Tier__c = 'Elite';
        ms.Current_status_of_alert__c = 'In Progress';
        update ms;
        //for existing contactg
        ms.clear();
        ms =  DataFactoryTest.SurveyResponseIns(ms,'002','New');
        Insert ms;
		// Auto Clsoed case
		ms.clear();
        ms =  DataFactoryTest.SurveyResponseIns(ms,'003','Closed');
        Insert ms;
        
    }
    
}